version: 0.0
os: linux
files:
  - source: ./
    destination: /wwwroot/
  - source: src/scripts/WeatherForecastApi.Web.service
    destination: /etc/systemd/system/
hooks:
  ApplicationStart:
    - location: ./scripts/application-start.sh
      timeout: 120
      runas: root
