version: 0.0
os: linux
files:
  - source: src
    destination: /wwwroot/
  - source: scripts/weather.service
    destination: /etc/systemd/system
hooks:
  ApplicationStart:
    - location: scripts/application-start.sh
      timeout: 120
      runas: root
