version: 0.0
os: linux
files:
  - source: src
    destination: /wwwroot/
  - source: scripts/webapi.service
    destination: /etc/systemd/system
hooks:
  BeforeInstall:
    - location: scripts/before-install.sh
      timeout: 120
      runas: root
  ApplicationStop:
    - location: scripts/stop_app.sh
      timeout: 120
      runas: root
  ApplicationStart:
    - location: scripts/application-start.sh
      timeout: 120
      runas: root
